### ISSUE TITLE
[Client] 날씨 API , Navigator, 사용자 정보 전달(Select.js)

### ISSUE THREAD

**Issue by Jeong-HW** [codestates/menuDao-client#32]
### **TODO**

- [x]  Nav.js (Navigator) CSS 적용
- [x]  날씨 API 구현 
- [x] Select.js에서 axios로 정보 전달 기능 구현
