### ISSUE TITLE
[TODO] ToDo list

### ISSUE THREAD

**Issue by allofhyuk** [codestates/menuDao-client#6]
### **TODO**

- [x]  기분관련 스키마 작성.
- [x]  nodejs, npm 버전 맞추기.
- [x]  오전 중 SR 제출.
